version: '3'
services:
  restapi:
    build:
      context: great-movies-core
      dockerfile: Dockerfile
    ports :
      - "1256:3000"
    links:
      - mongo_db
    networks:
      - webappnetwork
  webapp:
    build:
      context: great-movies-client
      dockerfile: Dockerfile
    ports :
      - "5000:4200"
    networks:
      - webappnetwork
  mongo_db:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - webappnetwork
networks:
  webappnetwork:
      driver: bridge
