version: '3'
services:
  mongo_db:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - webappnetwork
  mongo-seed:
    build : ./mongo-seed
    links:
      - mongo_db
    networks:
      - webappnetwork
  restapi:
    build:
      context: great-movies-core
      dockerfile: Dockerfile
    ports :
      - "3000:3000"
    links:
      - mongo-seed
    networks:
      - webappnetwork
  # webapp:
  #   build:
  #     context: great-movies-client
  #     dockerfile: Dockerfile
  #   ports :
  #     - "4200:4200"
  #   links:
  #     - restapi
  #   networks:
  #     - webappnetwork
networks:
  webappnetwork:
      driver: bridge
