version: '3'
services:
  restapi:
    build:
      context: great-movies-core
      dockerfile: Dockerfile
    ports :
      - "3000:3000"
  webapp:
    build:
      context: great-movies-client
      dockerfile: Dockerfile
    ports :
      - "4200:4200"