version: '3'
services:
  restapi:
    build:
      context: great-movies-core
      dockerfile: Dockerfile
    ports :
      - "3000:3000"
    links:
      - mongo
    networks:
      - webappnetwork
  webapp:
    build:
      context: great-movies-client
      dockerfile: Dockerfile
    ports :
      - "4200:4200"
    links:
      - restapi
    networks:
      - webappnetwork
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - webappnetwork
networks:
  webappnetwork:
      driver: bridge